#!/bin/bash

# Pick a display number manually
XVFB_DISPLAY=":99"

# Start virtual display with known XAUTHORITY
XAUTH_FILE="/tmp/xauth-vnc"
Xvfb $XVFB_DISPLAY -screen 0 480x800x24 -auth $XAUTH_FILE &
XVFB_PID=$!

# Generate xauth cookie
xauth -f $XAUTH_FILE generate $XVFB_DISPLAY . trusted

# Start vncviewer inside virtual display
DISPLAY=$XVFB_DISPLAY XAUTHORITY=$XAUTH_FILE \
vncviewer -ViewOnly=1 -Fullscreen=1 192.168.4.101:5900 -passwd ~/.vnc/passwd &
VNC_PID=$!

# Give it a few seconds to render
sleep 5

# Start FFmpeg to grab from the virtual display
DISPLAY=$XVFB_DISPLAY XAUTHORITY=$XAUTH_FILE \
ffmpeg -f x11grab -r 10 -s 480x800 -i $XVFB_DISPLAY \
  -c:v h264_vaapi -vf 'format=nv12,hwupload' \
  -b:v 1M -maxrate 1M -bufsize 2M -g 30 -sc_threshold 0 \
  -hls_time 4 -hls_list_size 6 -hls_flags delete_segments+append_list \
  -hls_segment_filename ~/vnc-hls/hls/lane1_%03d.ts \
  ~/vnc-hls/hls/lane1.m3u8

# Clean up
kill $VNC_PID
kill $XVFB_PID
rm -f $XAUTH_FILE
EOF

