github.com:
    users:
        kookaburrabarrel:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: kookaburrabarrel
